/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import classes.Compra;
import classes.CompraItem;
import classes.ItemVendido;
import classes.Pessoa;
import javax.swing.JFrame;
import persistencia.ServicoCompra;

/**
 *
 * @author Christian
 */
public class frm_rel_comprasEfetuadas extends javax.swing.JFrame {

    private boolean relCompras = true;
    private boolean relPessoaFisicaMaisComprou = false;
    private boolean relPessoaJuridicaMenosComprou = false;
    private boolean relProdutos = false;

    public void inicializaControles() {
        jTextRel.setEditable(false);
        if (relCompras) {
            carregaCompras();
        }
        if (relProdutos) {
            carregaProdutos();
        }
        if (relPessoaFisicaMaisComprou) {
            carregaPessoaFisicaMaisComprou();
        }
        if (relPessoaJuridicaMenosComprou) {
            carregaPessoaJuridicaMenosComprou();
        }
    }

    public void setPessoaFisicaMaisComprou() {
        relCompras = false;
        relPessoaFisicaMaisComprou = true;
        relPessoaJuridicaMenosComprou = false;
        relProdutos = false;
        jLabelTituloRel.setText("Pessoa Física que mais efetuou compras");
    }

    public void setPessoaJuridicaMenosComprou() {
        relCompras = false;
        relPessoaFisicaMaisComprou = false;
        relPessoaJuridicaMenosComprou = true;
        relProdutos = false;
        jLabelTituloRel.setText("Pessoa Jurídica que efetuou menos compras");
    }

    public void setRelacaoProdutos() {
        relCompras = false;
        relPessoaFisicaMaisComprou = false;
        relPessoaJuridicaMenosComprou = false;
        relProdutos = true;
        jLabelTituloRel.setText("Relação de Produtos (Itens) vendidos");
    }

    /**
     * Creates new form frm_rel_comprasEfetuadas
     */
    public frm_rel_comprasEfetuadas() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void carregaCompras() {
        jTextRel.removeAll();
        ServicoCompra srv = new ServicoCompra();
        String str = "";

        for (Compra c : srv.getCompras()) {
            str += "============================================\n";
            str += c.toString();
            str += "\n\nITENS: \n";
            for (CompraItem i : c.getItens()) {
                str += i.toString() + "\n\n";
            }
        }
        jTextRel.setText(str);
    }

    private void carregaProdutos() {
        jTextRel.removeAll();
        ServicoCompra srv = new ServicoCompra();
        String str = "";

        for (ItemVendido c : srv.getProdutosVendidos()) {
            str += c.toString()+"\n---------------------\n";
        }
        jTextRel.setText(str);
    }

    private void carregaPessoaFisicaMaisComprou() {
        jTextRel.removeAll();
        ServicoCompra srv = new ServicoCompra();
        String str = "";

        for (Pessoa c : srv.getPessoasFisicaMaisComprou()) {
            str += c.toString();
        }
        jTextRel.setText(str);
    }

    private void carregaPessoaJuridicaMenosComprou() {
        jTextRel.removeAll();
        ServicoCompra srv = new ServicoCompra();
        String str = "";

        for (Pessoa c : srv.getPessoasJuridicaMenosComprou()) {
            str += c.toString();
        }
        jTextRel.setText(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelTituloRel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextRel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório de Compras Efetuadas");

        jButtonFechar.setText("Fechar");
        jButtonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFecharMouseClicked(evt);
            }
        });
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );

        jLabelTituloRel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabelTituloRel.setText("Compras Efetuadas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabelTituloRel)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloRel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextRel.setColumns(20);
        jTextRel.setRows(5);
        jScrollPane1.setViewportView(jTextRel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFecharMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButtonFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_rel_comprasEfetuadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_rel_comprasEfetuadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_rel_comprasEfetuadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_rel_comprasEfetuadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_rel_comprasEfetuadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabelTituloRel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextRel;
    // End of variables declaration//GEN-END:variables
}
